apiVersion: v1
kind: Service
metadata:
  name: hello-api
  namespace: hello-api
spec:
  type: LoadBalancer
  selector:
    app: hello-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
